'use client';

import { useSearchParams } from 'next/navigation';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

export default function ReportView() {
  const searchParams = useSearchParams();
  const target = searchParams.get('target') || 'unknown';

  const handleDownloadPDF = () => {
    const input = document.getElementById('report-content');
    if (!input) return;
    html2canvas(input).then((canvas) => {
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      const width = pdf.internal.pageSize.getWidth();
      const height = (canvas.height * width) / canvas.width;
      pdf.addImage(imgData, 'PNG', 0, 0, width, height);
      pdf.save(`ZerOSINT_Report_${target}.pdf`);
    });
  };

  return (
    <div className="p-4 md:p-8">
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-terminal text-cyber-accent">Intelligence Report</h2>
        <button
          onClick={handleDownloadPDF}
          className="px-4 py-2 bg-cyber-accent text-cyber-bg rounded font-terminal text-sm"
        >
          Download PDF
        </button>
      </div>

      <div id="report-content" className="bg-cyber-surface p-6 rounded max-w-4xl mx-auto">
        <h1 className="text-3xl font-terminal text-cyber-accent mb-2">ZerOSINT Report</h1>
        <p className="text-cyber-low mb-6">Target: <span className="text-cyber-text">{target}</span></p>

        <div className="mb-6 p-4 bg-black/30 border border-cyber-low rounded">
          <h3 className="font-terminal text-cyber-highlight mb-2">Summary</h3>
          <p>
            The target shows consistent username reuse across GitHub and multiple forums,
            increasing attribution confidence. Public Git commits expose an email address
            linked to a personal domain.
          </p>
        </div>

        <div className="mb-6">
          <h3 className="font-terminal text-cyber-highlight mb-2">Risk Assessment</h3>
          <ul className="list-disc pl-5 space-y-1">
            <li>Identity traceability risk: High</li>
            <li>Public email exposure: Confirmed</li>
            <li>Cross-platform reuse: Detected</li>
          </ul>
        </div>

        <div className="text-xs text-cyber-low border-t pt-4 mt-8">
          <p>⚠️ Legal Disclaimer: This report contains only information from publicly available sources. It is intended for defensive cybersecurity, academic, or authorized investigative purposes only. The operator assumes no liability for misuse.</p>
          <p className="mt-2">Generated by ZerOSINT v1.0 • {new Date().toISOString().split('T')[0]}</p>
        </div>
      </div>
    </div>
  );
}